### ISSUE TITLE
Create List of clothing items

### ISSUE THREAD

**Issue by ando527** [ando527/DECO1800t39#4]

**Comment by AryanKamath04** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-GB style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>


Products   Category | Product   Name | Cost   (₹)
-- | -- | --
Head   gear | Baseball   Cap | ₹20
Head   gear | Bucket   hat | ₹20
Head   gear | Diamond   earrings | ₹50
Head   gear | Hoop   earrings | ₹20
Head   gear | Headphones | ₹60
Head   gear | Forehead   sweat band | ₹25
Shirt | T-shirt | ₹30
Shirt | Singlet | ₹20
Shirt | Formal   Shirt | ₹30
Shirt | Jacket | ₹40
Shirt | Robot   suit | ₹200
Sneakers | Boots | ₹40
Sneakers | Slippers | ₹20
Sneakers | Shoes | ₹30
Sneakers | Jet   shoes | ₹100



</div>


</body>

</html>
